services:
  backend:
    build:
      context: .
      dockerfile: rust-dev.Dockerfile
    user: "$USER_ID:$GROUP_ID"
    depends_on: [ db ]
    volumes:
      - .:/app
    working_dir: /app/backend
    command: cargo watch -x run
    environment:
      CARGO_HOME: .cargo
      DATABASE_URL: postgresql://nijsac@db/nijsac
      VERSION: development
    ports: [ "127.0.0.1:3000:3000" ]

  db:
    image: postgres:17
    pull_policy: always
    environment:
      POSTGRES_USER: nijsac
      POSTGRES_DB: nijsac
      TZ: Europe/Amsterdam
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: [ "127.0.0.1:5432:5432" ]