[licenses]
version = 2
private = { ignore = true }
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "Zlib",
    "BSD-2-Clause",
    "Apache-2.0 WITH LLVM-exception",
    "NCSA",
    "MPL-2.0"
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
